# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='recipes',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipes',
            name='datetime_modificated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
